parameters:
    app.mailer_from: '%env(MAILER_FROM)%'
    app.mailer_name: '%env(MAILER_NAME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\NotificationService:
        arguments:
            $mailerFrom: '%env(MAILER_FROM)%'
            $mailerName: '%env(MAILER_NAME)%'