<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260430092553 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE tasks_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE th_id_seq CASCADE');
        $this->addSql('ALTER TABLE tasks DROP CONSTRAINT fk_5058659714ddcdec');
        $this->addSql('ALTER TABLE tasks DROP CONSTRAINT fk_50586597a7e5433');
        $this->addSql('ALTER TABLE tasks DROP CONSTRAINT fk_50586597f0eb4cb');
        $this->addSql('ALTER TABLE th DROP CONSTRAINT fk_49e34767f675f31b');
        $this->addSql('ALTER TABLE th DROP CONSTRAINT fk_49e347678db60186');
        $this->addSql('DROP TABLE tasks');
        $this->addSql('DROP TABLE th');
        $this->addSql('ALTER TABLE project ALTER description TYPE TEXT');
        $this->addSql('ALTER TABLE project ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE tasks_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE th_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE tasks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, task_title VARCHAR(255) NOT NULL, task_desc TEXT NOT NULL, task_due_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, task_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, task_last_change TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, task_priority_id INT DEFAULT NULL, task_status_id INT DEFAULT NULL, task_project_id INT NOT NULL, "position" INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_50586597a7e5433 ON tasks (task_project_id)');
        $this->addSql('CREATE INDEX idx_5058659714ddcdec ON tasks (task_status_id)');
        $this->addSql('CREATE INDEX idx_50586597f0eb4cb ON tasks (task_priority_id)');
        $this->addSql('CREATE TABLE th (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, th_changelog VARCHAR(255) NOT NULL, th_updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, task_id INT DEFAULT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_49e347678db60186 ON th (task_id)');
        $this->addSql('CREATE INDEX idx_49e34767f675f31b ON th (author_id)');
        $this->addSql('ALTER TABLE tasks ADD CONSTRAINT fk_5058659714ddcdec FOREIGN KEY (task_status_id) REFERENCES status (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tasks ADD CONSTRAINT fk_50586597a7e5433 FOREIGN KEY (task_project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tasks ADD CONSTRAINT fk_50586597f0eb4cb FOREIGN KEY (task_priority_id) REFERENCES priority (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE th ADD CONSTRAINT fk_49e34767f675f31b FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE th ADD CONSTRAINT fk_49e347678db60186 FOREIGN KEY (task_id) REFERENCES tasks (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project ALTER description TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE project ALTER created_at TYPE DATE');
    }
}
