<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260428070954 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, position INT NOT NULL, priority_id INT DEFAULT NULL, status_id INT DEFAULT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_527EDB25497B19F9 ON task (priority_id)');
        $this->addSql('CREATE INDEX IDX_527EDB256BF700BD ON task (status_id)');
        $this->addSql('CREATE INDEX IDX_527EDB25166D1F9C ON task (project_id)');
        $this->addSql('CREATE TABLE task_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, changelog VARCHAR(255) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, task_id INT DEFAULT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_385B5AA18DB60186 ON task_history (task_id)');
        $this->addSql('CREATE INDEX IDX_385B5AA1F675F31B ON task_history (author_id)');
        $this->addSql('CREATE TABLE user_task (user_id INT NOT NULL, task_id INT NOT NULL, PRIMARY KEY (user_id, task_id))');
        $this->addSql('CREATE INDEX IDX_28FF97ECA76ED395 ON user_task (user_id)');
        $this->addSql('CREATE INDEX IDX_28FF97EC8DB60186 ON user_task (task_id)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25497B19F9 FOREIGN KEY (priority_id) REFERENCES priority (id)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB256BF700BD FOREIGN KEY (status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_history ADD CONSTRAINT FK_385B5AA18DB60186 FOREIGN KEY (task_id) REFERENCES task (id)');
        $this->addSql('ALTER TABLE task_history ADD CONSTRAINT FK_385B5AA1F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE user_task ADD CONSTRAINT FK_28FF97ECA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_task ADD CONSTRAINT FK_28FF97EC8DB60186 FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_tasks DROP CONSTRAINT fk_b29a9ecfe3272d31');
        $this->addSql('ALTER TABLE user_tasks DROP CONSTRAINT fk_b29a9ecfa76ed395');
        $this->addSql('DROP TABLE user_tasks');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT fk_bf5476ca67b3b43d');
        $this->addSql('DROP INDEX idx_bf5476ca67b3b43d');
        $this->addSql('ALTER TABLE notification ALTER link DROP NOT NULL');
        $this->addSql('ALTER TABLE notification RENAME COLUMN users_id TO user_id');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
        $this->addSql('ALTER TABLE priority RENAME COLUMN priority_name TO name');
        $this->addSql('ALTER TABLE project RENAME COLUMN project_name TO name');
        $this->addSql('ALTER TABLE project RENAME COLUMN project_desc TO description');
        $this->addSql('ALTER TABLE project RENAME COLUMN project_created_at TO created_at');
        $this->addSql('ALTER TABLE role RENAME COLUMN role_name TO name');
        $this->addSql('ALTER TABLE status RENAME COLUMN status_name TO name');
        $this->addSql('ALTER TABLE tasks ALTER task_due_date DROP NOT NULL');
        $this->addSql('ALTER TABLE tasks ALTER task_project_id SET NOT NULL');
        $this->addSql('DROP INDEX uniq_identifier_email');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_tasks (user_id INT NOT NULL, tasks_id INT NOT NULL, PRIMARY KEY (user_id, tasks_id))');
        $this->addSql('CREATE INDEX idx_b29a9ecfe3272d31 ON user_tasks (tasks_id)');
        $this->addSql('CREATE INDEX idx_b29a9ecfa76ed395 ON user_tasks (user_id)');
        $this->addSql('ALTER TABLE user_tasks ADD CONSTRAINT fk_b29a9ecfe3272d31 FOREIGN KEY (tasks_id) REFERENCES tasks (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_tasks ADD CONSTRAINT fk_b29a9ecfa76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25497B19F9');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB256BF700BD');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25166D1F9C');
        $this->addSql('ALTER TABLE task_history DROP CONSTRAINT FK_385B5AA18DB60186');
        $this->addSql('ALTER TABLE task_history DROP CONSTRAINT FK_385B5AA1F675F31B');
        $this->addSql('ALTER TABLE user_task DROP CONSTRAINT FK_28FF97ECA76ED395');
        $this->addSql('ALTER TABLE user_task DROP CONSTRAINT FK_28FF97EC8DB60186');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE task_history');
        $this->addSql('DROP TABLE user_task');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA76ED395');
        $this->addSql('DROP INDEX IDX_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE notification ALTER link SET NOT NULL');
        $this->addSql('ALTER TABLE notification RENAME COLUMN user_id TO users_id');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT fk_bf5476ca67b3b43d FOREIGN KEY (users_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_bf5476ca67b3b43d ON notification (users_id)');
        $this->addSql('ALTER TABLE priority RENAME COLUMN name TO priority_name');
        $this->addSql('ALTER TABLE project ADD project_desc VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE project ADD project_created_at DATE NOT NULL');
        $this->addSql('ALTER TABLE project DROP description');
        $this->addSql('ALTER TABLE project DROP created_at');
        $this->addSql('ALTER TABLE project RENAME COLUMN name TO project_name');
        $this->addSql('ALTER TABLE role RENAME COLUMN name TO role_name');
        $this->addSql('ALTER TABLE status RENAME COLUMN name TO status_name');
        $this->addSql('ALTER TABLE tasks ALTER task_due_date SET NOT NULL');
        $this->addSql('ALTER TABLE tasks ALTER task_project_id DROP NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email)');
    }
}
